// Exercise 09.03.01.txt
// This program throws an error exception of type string.

#include <iostream>
#include <string>
using namespace std;

int gcf(int a, int b);

int main() {
    try {
        cout << "gcf(12, 18) = " << gcf(12, 18) << endl;
        cout << "gcf(125, 45) = " << gcf(125, 45) << endl;
        cout << "gcf(5, 0) = " << gcf(5, 0) << endl;
        return 0;
    }
    catch (string err) {
        cout << "EXCEPTION RAISED! " << endl;
        cout << err << endl;
        return -1;
    }
}

// GCF function.
// Note that when exception is thrown, a char* string must be
//  converted to type string.
// This conversion is not necessary if the exception object has
//  type char* to begin with.
//
int gcf(int a, int b) {
    if (b == 0)
        throw string("Attempt to divide by zero");
    if (a % b == 0)
        return b;
    else
        return gcf(b, a % b);
}
